twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'
    paths:
        'assets/images': images
    globals:
        pathToWeb: "%kernel.project_dir%/public"

when@test:
    twig:
        strict_variables: true
