# config/packages/workflow.yaml
framework:
    workflows:
        atencion_reclamo:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'estado'
            # The "supports" option is useful only if you are using Twig functions ('workflow_*')
            supports:
                - App\Entity\Reclamo
            initial_marking: Creado
            places:
                - Creado
                - En Guardia
                - Atendiendo
                - Siniestro
                - Mantenimiento
                - Finalizado
            transitions:
                to_derived:
                    from: Creado
                    to: En Guardia
                to_success:
                    from: En Guardia
                    to: Atendiendo
                to_close:
                    from: Atendiendo
                    to: Finalizado
                to_siniestro:
                    from: Creado
                    to: Siniestro
                to_close_siniestro:
                    from: Siniestro
                    to: Finalizado
                to_mantenimiento:
                    from: Creado
                    to: Mantenimiento
                to_close_mantenimiento:
                    from: Mantenimiento
                    to: Finalizado



